# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
 facebook_key: 712003092272292
 facebook_secret: 57e498a3ecb759d501df1661c271a165
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
